name: Gateway-Service CD Flow

on:
  workflow_run:
    workflows: ["Gateway-Service CI Flow"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy-to-production:
    name: Deploy Gateway Service to Production Server
    runs-on: self-hosted

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy Locally on Self-Hosted
        env:
          IMAGE_TAG: ${{ github.event.workflow_run.head_sha }}
        run: |
          set -e
          cd /Users/hork/Downloads/GitOps-Manifest/
          IMAGE_TAG=$IMAGE_TAG gmake up-gateway-service
